### PR TITLE
Upgrade purs to 0.13 and expo to 34

### PR DESCRIPTION
**Pull request by andywhite37**
Hi @dwhitney!

It's a blast from the Pellucid past! Thanks for making this library, I just got it all upgraded and working and I'm excited to play around with it. This looks like a real labor of love, so thanks for taking the time to figure all this stuff out. Are you still viewing this repo as a good approach for cross-platform mobile apps in PureScript, or have you moved onto something else at this point?

For this PR, I updated spago stuff, npm libs, etc. and I also added the `expo start:web` stuff to allow apps to be previewed via web.  The examples both have a new `npm run web` command to run that.

- Ran `spago upgrade-set` in each place to get spago deps up-to-date
  - This also required some reworking of the packages.dhall files to work with latest spago format
- Ran `npm-check-updates -u` in various places to update package.jsonlibs
- Ran the [expo update steps](https://docs.expo.io/versions/latest/workflow/upgrading-expo-sdk-walkthrough/) to go from expo 32 to 36
- Removed yarn.lock and replaced with package-lock.json, because things were bitching about yarn and npm lock conflicts, and things seemed to want to run npm (?)

### CODE REVIEW

**Comment by dwhitney** [comment]
Hey Andy! I saw this over the weekend but them forgot about it - apologies for the late response.

I'll take a look at this PR tonight, but I don't foresee any issues. BTW, I am working with Earle now and in about a month we're going to kick off a project that will use this quite a bit. I may make some changes to it - like breaking the library out into multiple files, etc.

**Comment by f-f** [comment]
@dwhitney I was looking into this project for a mobile app, are the improvements you mention above still happening? If yes, I'll wait for them, otherwise it looks like I could work off this branch?

**Comment by dwhitney** [comment]
I have no idea when I'll get around to looking at this, so go ahead and do
whatever you want. I'm happy to transfer ownership of you want too

D

**Comment by andywhite37** [comment]
For what it's worth, I would consider this PR to be fairly safe to merge. All I did was update some of the library versions, and migrate the spago files into the more recent way of doing things.

I was able to get everything compiling and running locally.

**Comment by FranklinChen** [comment]
I'm curious what the general status of this project is.

**Comment by dwhitney** [comment]
Well it works, but I'm not sure I'll have much time to work on it. I'm
happy to give it up to someone else.

**Comment by f-f** [comment]
@dwhitney it looks like community interest in this stuff is quite consistent so I wouldn't like this to feel abandoned - I guess I could take on commit access (or admin/ownership if you want to get rid of it) to merge pending PRs and update this otherwise. How does this sound?

**Comment by dwhitney** [comment]
Hey yeah that would be awesome! Sorry for the late reply. I lost my job
during this dumb pandemic. Searching for a job while homeschooling two kids
has me feeling like I'm drowning.

D

**Comment by dwhitney** [comment]
I'll transfer access in a bit.

**Comment by f-f** [comment]
@dwhitney no worries at all for the delay, and thank you for sharing where you're at - indeed this global reshuffling is hitting quite hard pretty much everyone.
I'm sorry to hear you lost your job and wish you all the best to navigate the next months, hopefully we'll get out of this soon :slightly_smiling_face: :heart:

**Comment by f-f** [comment]
Thanks again @dwhitney!

@andywhite37 this looks great to me, merging :slightly_smiling_face:

**Pull request merged**
